name: Secret File Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Transfer environment files
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        echo "${{ secrets.ESLINTRC_JSON }}" > .eslintrc.json
        echo "${{ secrets.PROD_ENV }}" > .prod.env
        echo "${{ secrets.NOTES_SERVER_SG_KEY_PEM }}" > notes-server-sg-key.pem
        scp .env .eslintrc.json .prod.env notes-server-sg-key.pem ubuntu@ip-172-31-29-202:/path/to/notes-app-back-end/
